# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import image_upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0003_auto_20170720_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipImageUploaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(upload_to=image_upload.models.format_uploaded_filename, verbose_name='Select a ZIP File & Click POST')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageUploaded',
        ),
    ]
