# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import image_upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0005_auto_20170720_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipimageuploaded',
            name='zip_file',
            field=models.FileField(unique=True, upload_to=image_upload.models.format_uploaded_filename, verbose_name='CHOOSE ZIP FILE'),
        ),
    ]
